version: "3.8"

services:
  # Database
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: myapp_development,myapp_test
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/docker/create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-databases.sh
    ports:
      - "5432:5432"
    networks:
      - fullstack-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Rails API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0"
    volumes:
      - ./backend:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.development
    environment:
      RAILS_ENV: development
      RAILS_LOG_TO_STDOUT: 1
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
    networks:
      - fullstack-network
    stdin_open: true
    tty: true

  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:3000
    networks:
      - fullstack-network
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data:
  bundle_cache:

networks:
  fullstack-network:
    driver: bridge
