# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

require:
  - rubocop-rails
  - rubocop-performance
  # - rubocop-rspec   # descomente se você instalou

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "tmp/**/*"

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Rails:
  Enabled: true

Rails/StrongParametersExpect:
  Enabled: false
# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
